config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  get 'pages/responsibility'

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def responsibility
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tadacon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
      <div class="container-fluid">
         <div class="navbar-brand">
         <%= link_to "Tada Con"%>
         	
         </div>
        
          <ul class="nav navbar-nav navbar-right">
             <li><%= link_to "HOME", pages_home_path %></li>
             <li><%= link_to "ABOUT US" , pages_about_path %></li>
             <li><%= link_to "RESPONSBILITY" , pages_responsibility_path %></li>
             <li><%= link_to "CONTACT US" , pages_contact_path %></li>
          </ul>
       
      </div>
  </nav>
    <section class="round">
  	  <%= yield %>
     </section>
</body>
</html>

app/views/pages/about.html.erb
 <h1>about</h1>
 <p> This is the about us page for the Tattooed shoreditch truffaut, godard selvage knausgaard wayfarers kale chips. Keffiyeh chambray XOXO, meh kinfolk blue bottle PBR&B selvage hashtag. Williamsburg 90's tousled pop-up. Post-ironic food truck occupy selvage. Synth master cleanse ethical, austin food truck irony YOLO raw denim keffiyeh pitchfork craft beer brunch tofu.
 
Synth scenester freegan, viral crucifix semiotics yr. Wayfarers 8-bit williamsburg, cardigan iPhone street art ugh viral polaroid pop-up dreamcatcher. Cray poutine trust fund heirloom, keytar freegan put a bird on it. Chillwave lo-fi hashtag, bitters hoodie craft beer pitchfork readymade heirloom. Echo park VHS hammock, you probably haven't heard of them gluten-free dreamcatcher retro. Narwhal vinyl synth, bushwick photo booth actually cray polaroid XOXO put a bird on it tofu bespoke direct trade drinking vinegar. Mlkshk freegan authentic irony, cornhole pop-up portland brunch.

Waistcoat hoodie keytar, hammock 8-bit roof party sustainable meggings fashion axe trust fund tacos. Hoodie chicharrones chartreuse cronut, tote bag food truck mumblecore single-origin coffee meggings VHS lumbersexual squid. Tattooed shoreditch truffaut, godard selvage knausgaard wayfarers kale chips. Keffiyeh chambray XOXO, meh kinfolk blue bottle PBR&B selvage hashtag. Williamsburg 90's tousled pop-up. Post-ironic food truck occupy selvage. Synth master cleanse ethical, austin food truck irony YOLO raw denim keffiyeh  <a href="http://www.facebook.com/emma.hailu/"> Zemin Daycare and Kindergarten </a>
 </p>

app/views/pages/contact.html.erb
<h1>contact</h1>
 <p> This is the contact us page for the 

    Humblebrag Time!
    Twitter

Synth scenester freegan, viral crucifix semiotics yr. Wayfarers 8-bit williamsburg, cardigan iPhone street art ugh viral polaroid pop-up dreamcatcher. Cray poutine trust fund heirloom, keytar freegan put a bird on it. Chillwave lo-fi hashtag, bitters hoodie craft beer pitchfork readymade heirloom. Echo park VHS hammock, you probably haven't heard of them gluten-free dreamcatcher retro. Narwhal vinyl synth, bushwick photo booth actually cray polaroid XOXO put a bird on it tofu bespoke direct trade drinking vinegar. Mlkshk freegan authentic irony, cornhole pop-up portland brunch.

Waistcoat hoodie keytar, hammock 8-bit roof party sustainable meggings fashion axe trust fund tacos. Hoodie chicharrones chartreuse cronut, tote bag food truck mumblecore single-origin coffee meggings VHS lumbersexual squid. Tattooed shoreditch truffaut, godard selvage knausgaard wayfarers kale chips. Keffiyeh chambray XOXO, meh kinfolk blue bottle PBR&B selvage hashtag. Williamsburg 90's tousled pop-up. Post-ironic food truck occupy selvage. Synth master cleanse ethical, austin food truck irony YOLO raw denim keffiyeh  <a href="http://www.facebook.com/emma.hailu"> Tada con</a> +251914843364
</p>

app/views/pages/home.html.erb
<h1>home</h1>
<p> This is the home page for the Keytar kombucha four dollar toast chartreuse kogi beard, ennui tilde butcher occupy chillwave 8-bit normcore drinking vinegar hella. Neutra actually stumptown, you probably haven't heard of them helvetica semiotics everyday carry vinyl brooklyn bespoke locavore ugh meh cornhole. Keffiyeh blue bottle art party, butcher squid hoodie tofu. Tacos keytar shabby chic messenger bag blog. Offal normcore tote bag chartreuse. Drinking vinegar paleo twee polaroid craft beer, occupy aesthetic cardigan synth irony artisan fingerstache shoreditch disrupt iPhone. Brooklyn raw denim distillery, iPhone +1 gluten-free pop-up. <a href="https://www.facebook.com/emma.hailu/"> Tadacon</a>
</p>

app/views/pages/responsibility.html.erb
<h1>Pages#responsibility</h1>
<p>Find me in app/views/pages/responsibility.html.erb</p>